name: Deploy
description: 'Deploy Various Environments'
runs-on: ubuntu-latest
timeout-minutes: 15
inputs:
  bucket-name:
    description: 'S3 Bucket For Storing Assets'
    required: true
  iam-role:
    description: 'ARN of IAM Role to Assume'
    required: true
  sentry-auth-token:
    description: 'Sentry authentication token'
    required: true
  is-preview:
    description: Boolean describing if this is a preview deployment
    required: false
    default: false
  bucket-region:
    required: false
    default: 'us-west-2'
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Extract Deployment Info
      id: deployment_info
      uses: ./.github/actions/deployment_info
    - name: Download Build Assets Artifact
      uses: actions/download-artifact@v3
      with:
        name: build-artifact
        path: build/
    - name: Add Deployment Version File To Assets
      shell: bash
      working-directory: build
      run: echo "${{ steps.deployment_info.outputs.short_sha }}" > deployment.txt
    # - name: Configure AWS Credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     role-to-assume: ${{ inputs.iam-role }}
    #     aws-region: ${{ inputs.bucket-region }}
    - name: Upload Assets
      shell: bash
      run: |
        if [ "${{ inputs.is-preview }}" == 'false' ]; then
          echo "aws s3 sync ./build s3://${{ inputs.bucket-name }}/builds/${{ steps.deployment_info.outputs.short_sha }}"
          echo "aws s3 sync ./build s3://${{ inputs.bucket-name }}/active --delete"
        else
          echo "aws s3 sync ./build s3://${{ inputs.bucket-name }}/previews/${{ steps.deployment_info.outputs.short_sha }}"
        fi

    - name: Create Sentry Release
      if: ${{ inputs.is-preview == 'false' }}
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ inputs.sentry-auth-token }}
        SENTRY_ORG: cadence
        SENTRY_PROJECT: falcon
      with:
        ignore_empty: true
        sourcemaps: ./build
        environment: ${{ env.REACT_APP_ENVIRONMENT }}
        version: ${{ env.REACT_APP_VERSION }}
    - name: Update Commit Status
      if: ${{ success() }} && "${{ inputs.is-preview }}" == 'true'
      shell: bash
      run: |
        curl \
          -i -H "Authorization: token ${{ github.token }}" \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/mcclayton/gh-deployments/statuses/${{ steps.deployment_info.outputs.full_sha }} \
          -d "{\"state\":\"success\", \"context\": \"Preview Environment\", \"target_url\": \"https://${{ steps.deployment_info.outputs.short_sha }}.preview.my.cadence.care\", \"description\": \"View details for preview environment\"}"
