name: CI+CD
on:
  push:
    branches:
      - main
      - develop
    tags:
      # Run when pushing release candidate tags
      - '[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+'
  pull_request:
    branches:
      - main
      - develop
jobs:
  setup_workspace:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Workspace
        uses: ./.github/actions/setup-node-workspace
  build:
    needs: setup_workspace
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Workspace (From Cache)
        uses: ./.github/actions/setup-node-workspace
      - name: Build
        run: npm run build --if-present
        env:
          REACT_APP_WELCOME_MESSAGE: ${{ secrets.REACT_APP_WELCOME_MESSAGE }}
      - name: Persist Build Assets Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build
          retention-days: 1
  deployment_info:
    needs: setup_workspace
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      full_sha: ${{ steps.git_info.outputs.full_sha }}
      short_sha: ${{ steps.git_info.outputs.short_sha }}
      deployment_env: ${{ steps.deployment_info.outputs.env }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Extract Git Info
        id: git_info
        shell: bash
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "push" ]]; then
            SHA=$GITHUB_SHA
          elif [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            SHA=${{ github.event.pull_request.head.sha }}
          fi
          echo "::set-output name=full_sha::$(git rev-parse "$SHA")"
          echo "::set-output name=short_sha::$(git rev-parse --short=7 "$SHA")"
      - name: Extract Deployment Info
        id: deployment_info
        shell: bash
        run: |
          if [ ${{ github.event_name }} == 'push' && ${{ github.ref }} == 'refs/heads/develop' ]; then
            echo "::set-output name=env::development"
          elif [ ${{ github.event_name }} == 'push' && ${{ github.ref }} == 'refs/heads/main' ]; then
            echo "::set-output name=env::production"
          elif [[ ${{ github.event_name }} == 'push' && "${{ github.event.ref }}" =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+$ ]]; then
            echo "::set-output name=env::qa"
          else
            echo "::set-output name=env::preview"
          fi
  deploy:
    needs:
      - deployment_info
      - build
    if: ${{ needs.deployment_info.outputs.deployment_env == 'development' ||
          needs.deployment_info.outputs.deployment_env == 'qa' ||
          needs.deployment_info.outputs.deployment_env == 'production' }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.deployment_info.outputs.deployment_env }}
      url: "https://michaelcclayton.com?environment=${{ needs.deployment_info.outputs.deployment_env }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          bucket-name: ${{ needs.deployment_info.outputs.deployment_env }}-bucket
          iam-role: arn:aws:iam::1:role/FakeServiceAccount
        env:
          REACT_APP_WELCOME_MESSAGE: ${{ secrets.REACT_APP_WELCOME_MESSAGE }}
